# Generated by Django 5.2.8 on 2026-01-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
